debian-gcc:
  image: registry.gitlab.com/goodvibes/goodvibes/debian:buster
  stage: build
  script:
    - bash -x ./.gitlab-ci/build.sh

debian-clang:
  image: registry.gitlab.com/goodvibes/goodvibes/debian:buster
  stage: build
  only: [ tags ]
  variables:
    CC: clang
  script:
    - bash -x ./.gitlab-ci/build.sh

fedora-gcc:
  image: registry.gitlab.com/goodvibes/goodvibes/fedora:28
  stage: build
  only: [ tags ]
  script:
    - bash -x ./.gitlab-ci/build.sh

fedora-clang:
  image: registry.gitlab.com/goodvibes/goodvibes/fedora:28
  stage: build
  only: [ tags ]
  variables:
    CC: clang
  script:
    - bash -x ./.gitlab-ci/build.sh
