fedora:
  image: registry.gitlab.com/goodvibes/goodvibes/fedora:28
  stage: build
  script:
    - bash -x ./.gitlab-ci/build.sh

debian:
  image: registry.gitlab.com/goodvibes/goodvibes/debian:buster
  stage: build
  script:
    - bash -x 'export CC=clang && ./.gitlab-ci/build.sh'
